version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: connectestudosbanco
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - rodrigo-network
  connectestudosbanco:
    image: rodrigocmo/first-project-with-intellij-javaspring
    restart: always
    build: ./first-project-with-intellij-javaspring
    working_dir: /first-project-with-intellij-javaspring
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://host.docker.internal:3308/connectestudosbanco?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root

    ports:
      - 80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - rodrigo-network
networks:
  rodrigo-network:
    driver: bridge